version: "3.8"

services:
  notification-services:
    container_name: notification-services
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_HOST: notification-db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: root
      DB_DATABASE: notification_system
    networks:
      - backend
    depends_on:
      - notification-db
      - rabbitmq

  notification-db:
    container_name: notification-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notification_system
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: 'bitnami/rabbitmq:3.13.7'
    platform: 'linux/arm64'
    container_name: notification-rabbitmq
    environment:
      RABBITMQ_ERL_COOKIE: 'securestring'
      RABBITMQ_USERNAME: 'guest'
      RABBITMQ_PASSWORD: 'guest'
      RABBITMQ_VHOST: '/'
      RABBITMQ_PLUGINS: "rabbitmq_management"
    ports:
      - "8080:15672"
      - "5672:5672"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
